---
###############################################################################
# Backup
###############################################################################
# Only backup SQLite databases and configuration file.

- name: 'Backup | filesystem | set backup location'
  when: >
    navidrome__cfg._backup_d | length > 0 and
    navidrome__cfg._backup_d != '/tmp'
  delegate_to: 'localhost'
  run_once: true
  ansible.builtin.file:
    path: '{{ navidrome__cfg._backup_d }}'
    mode: '0750'
    state: directory

- name: '{{ "Backup | fetch | " ~ navidrome___app._cfg }}'
  ansible.builtin.fetch:
    src: '{{ navidrome___app._cfg }}'
    dest: '{{
        navidrome__cfg._backup_d ~ "/" ~
        navidrome__srv._start ~ "_navidrome.toml"
      }}'
    fail_on_missing: false
    flat: true

# See services.yml for awk explanation.
- name: 'Backup | awk | DataFolder'
  ansible.builtin.shell: >-
    awk -F'[ ="]+' '$1 == "DataFolder" { print $2 }' {{ navidrome___app._cfg }}
  args:
    executable: '/bin/bash'
  changed_when: false
  register: navidrome__awk_data

- name: 'Backup | fetch | databases'
  ansible.builtin.fetch:
    src: '{{ navidrome__awk_data.stdout ~ "/" ~ item }}'
    dest: '{{
        navidrome__cfg._backup_d ~ "/" ~
        navidrome__srv._start ~ "_" ~ item
      }}'
    fail_on_missing: false
    flat: true
  loop:
    - 'navidrome.db'
    - 'navidrome.db-shm'
    - 'navidrome.db-wal'

- name: 'Backup | start'
  ansible.builtin.import_tasks: 'start.yml'

- name: 'Backup | success ✔'
  ansible.builtin.meta: 'end_host'
