---
###############################################################################
# Start
###############################################################################
# Start Navidrome services and confirm they are active and running.

- name: 'Start | systemd | start services'
  ansible.builtin.systemd:
    name: 'navidrome.service'
    enabled: true
    daemon_reload: true
    state: 'started'
  failed_when: false

- name: 'Start | fact | query services'
  ansible.builtin.service_facts:

- name: 'Start | assert | services running'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].state == 'running'
    fail_msg: |

      ✘ Service failed to start.
      {{ item }}
  loop:
    - 'navidrome.service'
