---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully.
#
# Tests:
# * Minimal navidrome.toml set (tested in converge).
# * User provided navidrome.toml set.
# * Navidrome services are active and running.
# * sqlite database exists in data directory.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        molecule_flg_inject: true
platforms:
  - name: 'navidrome-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    capabilities:
      - 'SYS_ADMIN'  # Required for systemd hardening.
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '4533:4533/tcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
