---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: Prepare | create cache'

    - name: 'Prepare | generate test CA private key'
      ansible.builtin.shell:
        'openssl genrsa 2048 > "{{ _test_cache }}/ca-key.pem"'
      args:
        creates: '{{ _test_cache }}/ca-key.pem'

    - name: 'Prepare | generate test CA certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-x509'
          - '-days'
          - '365000'
          - '-nodes'
          - '-subj'
          - '/C=US/ST=NY/L=NY/O=test/CN=test.example.com'
          - '-key'
          - '{{ _test_cache }}/ca-key.pem'
          - '-out'
          - '{{ _test_cache }}/ca.pem'
        creates: '{{ _test_cache }}/ca.pem'

    - name: 'Prepare | generate test client certificate request'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-newkey'
          - 'rsa:2048'
          - '-days'
          - '365000'
          - '-nodes'
          - '-subj'
          - '/C=US/ST=NY/L=NY/O=test/CN=test.example.com'
          - '-keyout'
          - '{{ _test_cache }}/server-key.pem'
          - '-out'
          - '{{ _test_cache }}/server-req.pem'
        creates: '{{ _test_cache }}/server-req.pem'

    - name: 'Prepare | sign test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'x509'
          - '-req'
          - '-in'
          - '{{ _test_cache }}/server-req.pem'
          - '-days'
          - '365000'
          - '-CA'
          - '{{ _test_cache }}/ca.pem'
          - '-CAkey'
          - '{{ _test_cache }}/ca-key.pem'
          - '-set_serial'
          - '01'
          - '-out'
          - '{{ _test_cache }}/server-cert.pem'
        creates: '{{ _test_cache }}/server-cert.pem'

- name: 'Prepare'
  hosts: 'navidrome-debian-13-all_options'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 977
        group: 977
        mode: '0755'
        state: 'directory'
