---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/navidrome/navidrome.toml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/navidrome/navidrome.toml'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/navidrome.toml.role_defaults"
          }}'
        test_file: '/etc/navidrome/navidrome.toml'
        test_owner: 'navidrome'
        test_group: 'navidrome'
        test_mode: '0640'
        test_state: 'file'
        test_diff: true

    - name: 'Verify | /var/lib/navidrome/navidrome.db'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /var/lib/navidrome/navidrome.db'
        test_file: '/var/lib/navidrome/navidrome.db'
        test_owner: 'navidrome'
        test_group: 'navidrome'
        test_mode: '0640'  # Restored files are set to 0640.
        test_state: 'file'
        test_diff: true
